// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import { getEnvFileOrder } from "./src/lib/env-files";

dotenv.config({ path: getEnvFileOrder(process.env.NODE_ENV) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun run prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
